Repository CloudSlang/cs-actions, pull requests merged in 2019-12, with the labels that each got.

#525 Added the Terraform Create Variable and Apply Run Cloudslang Operations
  cs-hashicorp-terraform/pom.xml
  cs-hashicorp-terraform/src/main/java/io/cloudslang/content/hashicorp/terraform/actions/runs/ApplyRun.java
  cs-hashicorp-terraform/src/main/java/io/cloudslang/content/hashicorp/terraform/actions/variables/CreateVariable.java
  cs-hashicorp-terraform/src/main/java/io/cloudslang/content/hashicorp/terraform/entities/ApplyRunInputs.java
  cs-hashicorp-terraform/src/main/java/io/cloudslang/content/hashicorp/terraform/entities/CreateVariableInputs.java
  cs-hashicorp-terraform/src/main/java/io/cloudslang/content/hashicorp/terraform/entities/TerraformCommonInputs.java
  cs-hashicorp-terraform/src/main/java/io/cloudslang/content/hashicorp/terraform/services/HttpCommons.java
  cs-hashicorp-terraform/src/main/java/io/cloudslang/content/hashicorp/terraform/services/RunImpl.java
  cs-hashicorp-terraform/src/main/java/io/cloudslang/content/hashicorp/terraform/services/VariableImpl.java
  cs-hashicorp-terraform/src/main/java/io/cloudslang/content/hashicorp/terraform/services/models/runs/ApplyRunRequestBody.java
  cs-hashicorp-terraform/src/main/java/io/cloudslang/content/hashicorp/terraform/services/models/variables/CreateVariableRequestBody.java
  cs-hashicorp-terraform/src/main/java/io/cloudslang/content/hashicorp/terraform/utils/Constants.java
  cs-hashicorp-terraform/src/main/java/io/cloudslang/content/hashicorp/terraform/utils/Descriptions.java
  cs-hashicorp-terraform/src/main/java/io/cloudslang/content/hashicorp/terraform/utils/HttpUtils.java
  cs-hashicorp-terraform/src/main/java/io/cloudslang/content/hashicorp/terraform/utils/Inputs.java
  cs-hashicorp-terraform/src/main/java/io/cloudslang/content/hashicorp/terraform/utils/InputsValidation.java
  cs-hashicorp-terraform/src/main/java/io/cloudslang/content/hashicorp/terraform/utils/Outputs.java
  cs-hashicorp-terraform/src/test/java/io/cloudslang/content/hashicorp/terraform/services/RunImplTest.java
  cs-hashicorp-terraform/src/test/java/io/cloudslang/content/hashicorp/terraform/services/VariableImplTest.java
Labels: dev

#529 updated files for operations Get Workspace Details and Get Run Details
  cs-hashicorp-terraform/src/main/java/io/cloudslang/content/hashicorp/terraform/actions/runs/GetRunDetails.java
  cs-hashicorp-terraform/src/main/java/io/cloudslang/content/hashicorp/terraform/actions/workspaces/GetWorkspaceDetails.java
  cs-hashicorp-terraform/src/main/java/io/cloudslang/content/hashicorp/terraform/entities/GetRunDetailsInputs.java
  cs-hashicorp-terraform/src/main/java/io/cloudslang/content/hashicorp/terraform/entities/GetWorkspaceDetailsInputs.java
  cs-hashicorp-terraform/src/main/java/io/cloudslang/content/hashicorp/terraform/entities/ListOAuthClientInputs.java
  cs-hashicorp-terraform/src/main/java/io/cloudslang/content/hashicorp/terraform/services/HttpCommons.java
  cs-hashicorp-terraform/src/main/java/io/cloudslang/content/hashicorp/terraform/services/RunImpl.java
  cs-hashicorp-terraform/src/main/java/io/cloudslang/content/hashicorp/terraform/services/WorkspaceImpl.java
  cs-hashicorp-terraform/src/main/java/io/cloudslang/content/hashicorp/terraform/utils/Constants.java
  cs-hashicorp-terraform/src/main/java/io/cloudslang/content/hashicorp/terraform/utils/Descriptions.java
  cs-hashicorp-terraform/src/main/java/io/cloudslang/content/hashicorp/terraform/utils/Inputs.java
  cs-hashicorp-terraform/src/main/java/io/cloudslang/content/hashicorp/terraform/utils/InputsValidation.java
  cs-hashicorp-terraform/src/test/java/io/cloudslang/content/hashicorp/terraform/services/RunImplTest.java
  cs-hashicorp-terraform/src/test/java/io/cloudslang/content/hashicorp/terraform/services/WorkspaceImplTest.java
Labels: dev

#530 changed sqljdbc4 dependency to mssql-jdbc 6.2.2.jre7 because of criti…
  cs-database/pom.xml
Labels: kind/bug

#531 updated to sync with reviews for get run details
  cs-hashicorp-terraform/src/main/java/io/cloudslang/content/hashicorp/terraform/actions/runs/GetRunDetails.java
  cs-hashicorp-terraform/src/main/java/io/cloudslang/content/hashicorp/terraform/utils/Descriptions.java
Labels: dev

#486 Implement Microsoft Office Excel operations
  cs-excel/header-definitions.xml
  cs-excel/license.template
  cs-excel/pom.xml
  cs-excel/src/main/java/io/cloudslang/content/excel/actions/AddCell.java
  cs-excel/src/main/java/io/cloudslang/content/excel/actions/CreateExcelFile.java
  cs-excel/src/main/java/io/cloudslang/content/excel/actions/DeleteCell.java
  cs-excel/src/main/java/io/cloudslang/content/excel/actions/GetCell.java
  cs-excel/src/main/java/io/cloudslang/content/excel/actions/GetRowIndexByCondition.java
  cs-excel/src/main/java/io/cloudslang/content/excel/actions/ModifyCell.java
  cs-excel/src/main/java/io/cloudslang/content/excel/entities/AddCellInputs.java
  cs-excel/src/main/java/io/cloudslang/content/excel/entities/CreateExcelFileInputs.java
  cs-excel/src/main/java/io/cloudslang/content/excel/entities/DeleteCellInputs.java
  cs-excel/src/main/java/io/cloudslang/content/excel/entities/ExcelCommonInputs.java
  cs-excel/src/main/java/io/cloudslang/content/excel/entities/ExcelOperationException.java
  cs-excel/src/main/java/io/cloudslang/content/excel/entities/GetCellInputs.java
  cs-excel/src/main/java/io/cloudslang/content/excel/entities/GetRowIndexByConditionInputs.java
  cs-excel/src/main/java/io/cloudslang/content/excel/entities/ModifyCellInputs.java
  cs-excel/src/main/java/io/cloudslang/content/excel/services/AddCellService.java
  cs-excel/src/main/java/io/cloudslang/content/excel/services/CreateExcelFileService.java
  cs-excel/src/main/java/io/cloudslang/content/excel/services/DeleteCellService.java
  cs-excel/src/main/java/io/cloudslang/content/excel/services/ExcelServiceImpl.java
  cs-excel/src/main/java/io/cloudslang/content/excel/services/GetCellService.java
  cs-excel/src/main/java/io/cloudslang/content/excel/services/GetRowIndexByConditionService.java
  cs-excel/src/main/java/io/cloudslang/content/excel/services/ModifyCellService.java
  cs-excel/src/main/java/io/cloudslang/content/excel/utils/Constants.java
  cs-excel/src/main/java/io/cloudslang/content/excel/utils/Descriptions.java
  cs-excel/src/main/java/io/cloudslang/content/excel/utils/Inputs.java
  cs-excel/src/main/java/io/cloudslang/content/excel/utils/InputsValidation.java
  cs-excel/src/main/java/io/cloudslang/content/excel/utils/Outputs.java
  pom.xml
Labels: kind/enhancement

#536 Created a Action for Delete variables.
  cs-hashicorp-terraform/src/main/java/io/cloudslang/content/hashicorp/terraform/actions/variables/DeleteVariable.java
  cs-hashicorp-terraform/src/main/java/io/cloudslang/content/hashicorp/terraform/services/VariableImpl.java
  cs-hashicorp-terraform/src/main/java/io/cloudslang/content/hashicorp/terraform/utils/Constants.java
  cs-hashicorp-terraform/src/main/java/io/cloudslang/content/hashicorp/terraform/utils/Descriptions.java
  cs-hashicorp-terraform/src/test/java/io/cloudslang/content/hashicorp/terraform/services/VariableImplTest.java
Labels: dev

#538 updated create variable operation to support multiple variable creation
  cs-hashicorp-terraform/src/main/java/io/cloudslang/content/hashicorp/terraform/actions/variables/CreateVariables.java
  cs-hashicorp-terraform/src/main/java/io/cloudslang/content/hashicorp/terraform/entities/TerraformVariableInputs.java
  cs-hashicorp-terraform/src/main/java/io/cloudslang/content/hashicorp/terraform/services/RunImpl.java
  cs-hashicorp-terraform/src/main/java/io/cloudslang/content/hashicorp/terraform/services/VariableImpl.java
  cs-hashicorp-terraform/src/main/java/io/cloudslang/content/hashicorp/terraform/services/models/runs/CreateRunBody.java
  cs-hashicorp-terraform/src/main/java/io/cloudslang/content/hashicorp/terraform/utils/Constants.java
  cs-hashicorp-terraform/src/main/java/io/cloudslang/content/hashicorp/terraform/utils/Descriptions.java
  cs-hashicorp-terraform/src/main/java/io/cloudslang/content/hashicorp/terraform/utils/Inputs.java
  cs-hashicorp-terraform/src/main/java/io/cloudslang/content/hashicorp/terraform/utils/InputsValidation.java
  cs-hashicorp-terraform/src/test/java/io/cloudslang/content/hashicorp/terraform/services/RunImplTest.java
  cs-hashicorp-terraform/src/test/java/io/cloudslang/content/hashicorp/terraform/services/VariableImplTest.java
Labels: dev

#539 added failure handling for create variable operation
  cs-hashicorp-terraform/src/main/java/io/cloudslang/content/hashicorp/terraform/actions/variables/CreateVariables.java
  cs-hashicorp-terraform/src/main/java/io/cloudslang/content/hashicorp/terraform/services/VariableImpl.java
  cs-hashicorp-terraform/src/main/java/io/cloudslang/content/hashicorp/terraform/utils/InputsValidation.java
Labels: dev

#541 Fixed scientific notation bug
  cs-excel/src/main/java/io/cloudslang/content/excel/services/GetCellService.java
Labels: kind/bug

#542 Created a action class for Applies and tested it.
  cs-hashicorp-terraform/src/main/java/io/cloudslang/content/hashicorp/terraform/actions/runs/ApplyDetails.java
  cs-hashicorp-terraform/src/main/java/io/cloudslang/content/hashicorp/terraform/entities/TerraformRunInputs.java
  cs-hashicorp-terraform/src/main/java/io/cloudslang/content/hashicorp/terraform/services/RunImpl.java
  cs-hashicorp-terraform/src/main/java/io/cloudslang/content/hashicorp/terraform/utils/Constants.java
  cs-hashicorp-terraform/src/main/java/io/cloudslang/content/hashicorp/terraform/utils/Descriptions.java
  cs-hashicorp-terraform/src/main/java/io/cloudslang/content/hashicorp/terraform/utils/Inputs.java
  cs-hashicorp-terraform/src/test/java/io/cloudslang/content/hashicorp/terraform/services/RunImplTest.java
Labels: dev

#545 updated action class for sensitive variable
  cs-hashicorp-terraform/src/main/java/io/cloudslang/content/hashicorp/terraform/actions/variables/CreateVariable.java
  cs-hashicorp-terraform/src/main/java/io/cloudslang/content/hashicorp/terraform/actions/variables/CreateVariables.java
  cs-hashicorp-terraform/src/main/java/io/cloudslang/content/hashicorp/terraform/entities/TerraformVariableInputs.java
  cs-hashicorp-terraform/src/main/java/io/cloudslang/content/hashicorp/terraform/services/VariableImpl.java
  cs-hashicorp-terraform/src/main/java/io/cloudslang/content/hashicorp/terraform/utils/Descriptions.java
  cs-hashicorp-terraform/src/main/java/io/cloudslang/content/hashicorp/terraform/utils/InputsValidation.java
  cs-hashicorp-terraform/src/test/java/io/cloudslang/content/hashicorp/terraform/services/VariableImplTest.java
Labels: dev
