Repository CloudSlang/cs-actions, pull requests merged in 2020-09, with the labels that each got.

#688 fix for issue - 867403 : Issue with OO base content 1.18.0 send mail …
  cs-mail/src/main/java/io/cloudslang/content/mail/services/SendMailService.java
  cs-mail/src/test/java/io/cloudslang/content/mail/services/SendMailServiceTest.java
Labels: dev

#690 Fixed json operation bugs
  cs-json/src/main/java/io/cloudslang/content/json/actions/GetArraySublistAction.java
  cs-json/src/main/java/io/cloudslang/content/json/actions/RemoveEmptyElementAction.java
  cs-json/src/main/java/io/cloudslang/content/json/entities/GetArraySublistInput.java
  cs-json/src/main/java/io/cloudslang/content/json/services/GetArraySublistService.java
  cs-json/src/main/java/io/cloudslang/content/json/services/JsonService.java
  cs-json/src/main/java/io/cloudslang/content/json/utils/ExceptionMsgs.java
  cs-json/src/main/java/io/cloudslang/content/json/validators/GetArraySublistValidator.java
Labels: kind/bug

#691 Fixed "plaintext connection" issue when using Outlook server
  cs-mail/src/main/java/io/cloudslang/content/mail/entities/GetMailAttachmentInput.java
  cs-mail/src/main/java/io/cloudslang/content/mail/entities/GetMailMessageCountInput.java
  cs-mail/src/main/java/io/cloudslang/content/mail/entities/GetMailMessageInput.java
  cs-mail/src/main/java/io/cloudslang/content/mail/entities/SendMailInput.java
  cs-mail/src/main/java/io/cloudslang/content/mail/services/SendMailService.java
  cs-mail/src/main/java/io/cloudslang/content/mail/sslconfig/SSLUtils.java
  cs-mail/src/main/java/io/cloudslang/content/mail/utils/ProxyUtils.java
  cs-mail/src/test/java/io/cloudslang/content/mail/sslconfig/SSLUtilsTest.java
Labels: kind/bug

#692 Refactor Mail operations to upgrade bcmail library to bcmail-jdk15on 1.60
  cs-mail/pom.xml
  cs-mail/src/main/java/io/cloudslang/content/mail/constants/SecurityConstants.java
  cs-mail/src/main/java/io/cloudslang/content/mail/entities/EncryptionAlgorithmsEnum.java
  cs-mail/src/main/java/io/cloudslang/content/mail/entities/GetMailMessageCountInput.java
  cs-mail/src/main/java/io/cloudslang/content/mail/entities/GetMailMessageInput.java
  cs-mail/src/main/java/io/cloudslang/content/mail/entities/SendMailInput.java
  cs-mail/src/main/java/io/cloudslang/content/mail/services/GetMailAttachmentService.java
  cs-mail/src/main/java/io/cloudslang/content/mail/services/GetMailMessageService.java
  cs-mail/src/main/java/io/cloudslang/content/mail/services/SendMailService.java
  cs-mail/src/main/java/io/cloudslang/content/mail/utils/SecurityUtils.java
Labels: dependencies, kind/enhancement
