Repository CloudSlang/cs-actions, pull requests merged in 2020-04, with the labels that each got.

#578 690586 Updated the maven.compiler.source plugin version to 1.8
  cs-amazon/pom.xml
  cs-xml/pom.xml
Labels: dependencies

#580 Fixes and feature added for cs-mail
  cs-mail/pom.xml
  cs-mail/src/main/java/io/cloudslang/content/mail/actions/GetMailAttachmentAction.java
  cs-mail/src/main/java/io/cloudslang/content/mail/actions/GetMailMessageAction.java
  cs-mail/src/main/java/io/cloudslang/content/mail/constants/InputNames.java
  cs-mail/src/main/java/io/cloudslang/content/mail/entities/GetMailAttachmentInput.java
  cs-mail/src/main/java/io/cloudslang/content/mail/entities/GetMailMessageInput.java
  cs-mail/src/main/java/io/cloudslang/content/mail/services/GetMailAttachmentService.java
  cs-mail/src/main/java/io/cloudslang/content/mail/sslconfig/EasyX509TrustManager.java
  cs-mail/src/main/java/io/cloudslang/content/mail/sslconfig/SSLUtils.java
  cs-mail/src/main/java/io/cloudslang/content/mail/utils/InputBuilderUtils.java
Labels: dev, kind/bug

#579 Updated the cs-commons version to 0.0.7
  cs-http-client/pom.xml
Labels: dependencies

#581 removing guava dependency
  cs-http-client/pom.xml
Labels: dependencies

#583 Updated cs-xml version to 0.0.15
  cs-amazon/pom.xml
Labels: dependencies

#585 ABBYY ProcessImage & ProcessTextField
  cs-abbyy/header-definitions.xml
  cs-abbyy/license.template
  cs-abbyy/pom.xml
  cs-abbyy/src/main/java/io/cloudslang/content/abbyy/actions/ProcessImageAction.java
  cs-abbyy/src/main/java/io/cloudslang/content/abbyy/actions/ProcessTextFieldAction.java
  cs-abbyy/src/main/java/io/cloudslang/content/abbyy/constants/ConnectionConstants.java
  cs-abbyy/src/main/java/io/cloudslang/content/abbyy/constants/ExceptionMsgs.java
  cs-abbyy/src/main/java/io/cloudslang/content/abbyy/constants/InputNames.java
  cs-abbyy/src/main/java/io/cloudslang/content/abbyy/constants/MiscConstants.java
  cs-abbyy/src/main/java/io/cloudslang/content/abbyy/constants/OutputNames.java
  cs-abbyy/src/main/java/io/cloudslang/content/abbyy/entities/AbbyyRequest.java
  cs-abbyy/src/main/java/io/cloudslang/content/abbyy/entities/AbbyyResponse.java
  cs-abbyy/src/main/java/io/cloudslang/content/abbyy/entities/ExportFormat.java
  cs-abbyy/src/main/java/io/cloudslang/content/abbyy/entities/ImageSource.java
  cs-abbyy/src/main/java/io/cloudslang/content/abbyy/entities/LocationId.java
  cs-abbyy/src/main/java/io/cloudslang/content/abbyy/entities/MarkingType.java
  cs-abbyy/src/main/java/io/cloudslang/content/abbyy/entities/ProcessImageInput.java
  cs-abbyy/src/main/java/io/cloudslang/content/abbyy/entities/ProcessTextFieldInput.java
  cs-abbyy/src/main/java/io/cloudslang/content/abbyy/entities/Profile.java
  cs-abbyy/src/main/java/io/cloudslang/content/abbyy/entities/Region.java
  cs-abbyy/src/main/java/io/cloudslang/content/abbyy/entities/TextType.java
  cs-abbyy/src/main/java/io/cloudslang/content/abbyy/entities/WriteTags.java
  cs-abbyy/src/main/java/io/cloudslang/content/abbyy/entities/WritingStyle.java
  cs-abbyy/src/main/java/io/cloudslang/content/abbyy/exceptions/AbbyySdkException.java
  cs-abbyy/src/main/java/io/cloudslang/content/abbyy/exceptions/ClientSideException.java
  cs-abbyy/src/main/java/io/cloudslang/content/abbyy/exceptions/ServerSideException.java
  cs-abbyy/src/main/java/io/cloudslang/content/abbyy/exceptions/ValidationException.java
  cs-abbyy/src/main/java/io/cloudslang/content/abbyy/services/AbstractPostRequestService.java
  cs-abbyy/src/main/java/io/cloudslang/content/abbyy/services/ProcessImageService.java
  cs-abbyy/src/main/java/io/cloudslang/content/abbyy/services/ProcessTextFieldService.java
  cs-abbyy/src/main/java/io/cloudslang/content/abbyy/utils/AbbyyResponseParser.java
  cs-abbyy/src/main/java/io/cloudslang/content/abbyy/utils/InputParser.java
  cs-abbyy/src/main/java/io/cloudslang/content/abbyy/utils/ResultUtils.java
  cs-abbyy/src/main/java/io/cloudslang/content/abbyy/utils/XmlResponseParser.java
  cs-abbyy/src/main/java/io/cloudslang/content/abbyy/validators/AbbyyRequestValidator.java
  cs-abbyy/src/main/java/io/cloudslang/content/abbyy/validators/AbbyyResultValidator.java
  cs-abbyy/src/main/java/io/cloudslang/content/abbyy/validators/JavaxXmlValidatorAdapter.java
  cs-abbyy/src/main/java/io/cloudslang/content/abbyy/validators/ProcessImageValidator.java
  cs-abbyy/src/main/java/io/cloudslang/content/abbyy/validators/ProcessTextFieldValidator.java
  cs-abbyy/src/main/resources/xml_result.xsd
  cs-abbyy/src/test/java/io/cloudslang/content/abbyy/services/AbstractPostRequestServiceTest.java
  cs-abbyy/src/test/java/io/cloudslang/content/abbyy/services/ProcessImageServiceTest.java
  cs-abbyy/src/test/java/io/cloudslang/content/abbyy/services/ProcessTextFieldServiceTest.java
  cs-abbyy/src/test/java/io/cloudslang/content/abbyy/utils/AbbyyResponseParserTest.java
  cs-abbyy/src/test/java/io/cloudslang/content/abbyy/utils/InputParserTest.java
  cs-abbyy/src/test/java/io/cloudslang/content/abbyy/utils/XmlResponseParserTest.java
  cs-abbyy/src/test/java/io/cloudslang/content/abbyy/validators/AbbyyRequestValidatorTest.java
  cs-abbyy/src/test/java/io/cloudslang/content/abbyy/validators/AbbyyResultValidatorTest.java
  cs-abbyy/src/test/java/io/cloudslang/content/abbyy/validators/JavaXmlValidatorAdapterTest.java
  cs-abbyy/src/test/java/io/cloudslang/content/abbyy/validators/ProcessImageValidatorTest.java
  cs-abbyy/src/test/java/io/cloudslang/content/abbyy/validators/ProcessTextFieldValidatorTest.java
  pom.xml
Labels: dev

#584 Added the Terraform Organization Operations
  cs-hashicorp-terraform/src/main/java/io/cloudslang/content/hashicorp/terraform/actions/organizations/CreateOrganization.java
  cs-hashicorp-terraform/src/main/java/io/cloudslang/content/hashicorp/terraform/actions/organizations/DeleteOrganization.java
  cs-hashicorp-terraform/src/main/java/io/cloudslang/content/hashicorp/terraform/actions/organizations/GetOrganizationDetails.java
  cs-hashicorp-terraform/src/main/java/io/cloudslang/content/hashicorp/terraform/actions/organizations/ListOrganizations.java
  cs-hashicorp-terraform/src/main/java/io/cloudslang/content/hashicorp/terraform/actions/organizations/UpdateOrganization.java
  cs-hashicorp-terraform/src/main/java/io/cloudslang/content/hashicorp/terraform/entities/TerraformOrganizationInputs.java
  cs-hashicorp-terraform/src/main/java/io/cloudslang/content/hashicorp/terraform/services/OrganizationImpl.java
  cs-hashicorp-terraform/src/main/java/io/cloudslang/content/hashicorp/terraform/services/models/organization/CreateOrganizationRequestBody.java
  cs-hashicorp-terraform/src/main/java/io/cloudslang/content/hashicorp/terraform/utils/Constants.java
  cs-hashicorp-terraform/src/main/java/io/cloudslang/content/hashicorp/terraform/utils/Descriptions.java
  cs-hashicorp-terraform/src/main/java/io/cloudslang/content/hashicorp/terraform/utils/Inputs.java
  cs-hashicorp-terraform/src/main/java/io/cloudslang/content/hashicorp/terraform/utils/InputsValidation.java
  cs-hashicorp-terraform/src/main/java/io/cloudslang/content/hashicorp/terraform/utils/Outputs.java
  cs-hashicorp-terraform/src/test/java/io/cloudslang/content/hashicorp/terraform/services/OrganizationImplTest.java
Labels: dev

#586 Added TLS enforcement to ABBYY
  cs-abbyy/src/main/java/io/cloudslang/content/abbyy/actions/ProcessImageAction.java
  cs-abbyy/src/main/java/io/cloudslang/content/abbyy/actions/ProcessTextFieldAction.java
  cs-abbyy/src/main/java/io/cloudslang/content/abbyy/constants/MiscConstants.java
  cs-abbyy/src/main/java/io/cloudslang/content/abbyy/services/AbstractPostRequestService.java
  cs-abbyy/src/main/java/io/cloudslang/content/abbyy/services/ProcessImageService.java
  cs-abbyy/src/main/java/io/cloudslang/content/abbyy/services/ProcessTextFieldService.java
Labels: kind/enhancement

#587 Fixed the email issue in Terraform Organization Operations
  cs-hashicorp-terraform/src/main/java/io/cloudslang/content/hashicorp/terraform/actions/organizations/CreateOrganization.java
  cs-hashicorp-terraform/src/main/java/io/cloudslang/content/hashicorp/terraform/actions/organizations/UpdateOrganization.java
  cs-hashicorp-terraform/src/main/java/io/cloudslang/content/hashicorp/terraform/services/OrganizationImpl.java
  cs-hashicorp-terraform/src/main/java/io/cloudslang/content/hashicorp/terraform/utils/Inputs.java
Labels: dev
