Repository CloudSlang/cs-actions, pull requests merged in 2020-06, with the labels that each got.

#602 Added configurationName input to PowerShell Script Action
  cs-powershell/src/main/java/io/cloudslang/content/actions/PowerShellScriptAction.java
  cs-powershell/src/main/java/io/cloudslang/content/entities/WSManRequestInputs.java
  cs-powershell/src/main/java/io/cloudslang/content/services/WSManRemoteShellService.java
  cs-powershell/src/main/java/io/cloudslang/content/utils/Constants.java
  cs-powershell/src/main/java/io/cloudslang/content/utils/WSManUtils.java
  cs-powershell/src/test/java/io/cloudslang/content/actions/PowerShellScriptActionTest.java
Labels: dev, kind/enhancement

#606 Updated the create instance operation.
  cs-oracle-cloud/src/main/java/io/cloudslang/content/oracle/oci/actions/instances/CreateInstance.java
  cs-oracle-cloud/src/main/java/io/cloudslang/content/oracle/oci/actions/instances/GetInstanceDetails.java
  cs-oracle-cloud/src/main/java/io/cloudslang/content/oracle/oci/actions/vnics/ListVnicAttachments.java
  cs-oracle-cloud/src/main/java/io/cloudslang/content/oracle/oci/entities/inputs/OCIInstanceInputs.java
  cs-oracle-cloud/src/main/java/io/cloudslang/content/oracle/oci/services/CounterImpl.java
  cs-oracle-cloud/src/main/java/io/cloudslang/content/oracle/oci/services/InstanceImpl.java
  cs-oracle-cloud/src/main/java/io/cloudslang/content/oracle/oci/utils/Constants.java
  cs-oracle-cloud/src/main/java/io/cloudslang/content/oracle/oci/utils/CounterProcessor.java
  cs-oracle-cloud/src/main/java/io/cloudslang/content/oracle/oci/utils/CounterSessionResource.java
  cs-oracle-cloud/src/main/java/io/cloudslang/content/oracle/oci/utils/Descriptions.java
  cs-oracle-cloud/src/main/java/io/cloudslang/content/oracle/oci/utils/Inputs.java
Labels: dev

#607 Updated create instance operation and added the counter operation.
  cs-oracle-cloud/src/main/java/io/cloudslang/content/oracle/oci/actions/instances/CreateInstance.java
  cs-oracle-cloud/src/main/java/io/cloudslang/content/oracle/oci/actions/utils/Counter.java
  cs-oracle-cloud/src/main/java/io/cloudslang/content/oracle/oci/actions/vnics/ListVnicAttachments.java
  cs-oracle-cloud/src/main/java/io/cloudslang/content/oracle/oci/services/InstanceImpl.java
Labels: dev

#609 Oci/instanceoperations
  cs-oracle-cloud/src/main/java/io/cloudslang/content/oracle/oci/actions/instances/CreateInstance.java
  cs-oracle-cloud/src/main/java/io/cloudslang/content/oracle/oci/actions/instances/GetInstanceDefaultCredentials.java
  cs-oracle-cloud/src/main/java/io/cloudslang/content/oracle/oci/actions/instances/GetInstanceDetails.java
  cs-oracle-cloud/src/main/java/io/cloudslang/content/oracle/oci/actions/instances/ListInstances.java
  cs-oracle-cloud/src/main/java/io/cloudslang/content/oracle/oci/actions/vnics/GetVnicDetails.java
  cs-oracle-cloud/src/main/java/io/cloudslang/content/oracle/oci/actions/vnics/ListVnicAttachments.java
  cs-oracle-cloud/src/main/java/io/cloudslang/content/oracle/oci/entities/inputs/OCICommonInputs.java
  cs-oracle-cloud/src/main/java/io/cloudslang/content/oracle/oci/entities/inputs/OCIListInstanceInputs.java
  cs-oracle-cloud/src/main/java/io/cloudslang/content/oracle/oci/services/HttpCommons.java
  cs-oracle-cloud/src/main/java/io/cloudslang/content/oracle/oci/services/InstanceImpl.java
  cs-oracle-cloud/src/main/java/io/cloudslang/content/oracle/oci/services/VnicImpl.java
  cs-oracle-cloud/src/main/java/io/cloudslang/content/oracle/oci/services/models/instances/CreateInstanceRequestBody.java
  cs-oracle-cloud/src/main/java/io/cloudslang/content/oracle/oci/utils/Constants.java
  cs-oracle-cloud/src/main/java/io/cloudslang/content/oracle/oci/utils/Descriptions.java
  cs-oracle-cloud/src/main/java/io/cloudslang/content/oracle/oci/utils/HttpUtils.java
  cs-oracle-cloud/src/main/java/io/cloudslang/content/oracle/oci/utils/Inputs.java
  cs-oracle-cloud/src/main/java/io/cloudslang/content/oracle/oci/utils/InputsValidation.java
  cs-oracle-cloud/src/main/java/io/cloudslang/content/oracle/oci/utils/Outputs.java
  cs-oracle-cloud/src/test/java/io/cloudslang/content/oracle/oci/utils/HttpUtilsTest.java
  cs-oracle-cloud/src/test/java/io/cloudslang/content/oracle/oci/utils/InputsValidationUtilsTest.java
Labels: dev

#610 Added unit test of createVM and added outputs for get vm details action.
  cs-nutanix-prism/src/main/java/io/cloudslang/content/nutanix/prism/actions/tasks/GetTaskDetails.java
  cs-nutanix-prism/src/main/java/io/cloudslang/content/nutanix/prism/actions/virtualmachines/CreateVM.java
  cs-nutanix-prism/src/main/java/io/cloudslang/content/nutanix/prism/actions/virtualmachines/GetVMDetails.java
  cs-nutanix-prism/src/main/java/io/cloudslang/content/nutanix/prism/entities/NutanixGetTaskDetailsInputs.java
  cs-nutanix-prism/src/main/java/io/cloudslang/content/nutanix/prism/service/TaskImpl.java
  cs-nutanix-prism/src/main/java/io/cloudslang/content/nutanix/prism/service/VMImpl.java
  cs-nutanix-prism/src/main/java/io/cloudslang/content/nutanix/prism/service/models/virtualmachines/CreateVMRequestBody.java
  cs-nutanix-prism/src/main/java/io/cloudslang/content/nutanix/prism/utils/Constants.java
  cs-nutanix-prism/src/main/java/io/cloudslang/content/nutanix/prism/utils/Descriptions.java
  cs-nutanix-prism/src/main/java/io/cloudslang/content/nutanix/prism/utils/HttpUtils.java
  cs-nutanix-prism/src/main/java/io/cloudslang/content/nutanix/prism/utils/Inputs.java
  cs-nutanix-prism/src/main/java/io/cloudslang/content/nutanix/prism/utils/Outputs.java
  cs-nutanix-prism/src/test/java/io/cloudslang/content/nutanix/prism/services/TaskImplTest.java
  cs-nutanix-prism/src/test/java/io/cloudslang/content/nutanix/prism/services/VMImplTest.java
  cs-nutanix-prism/src/test/java/io/cloudslang/content/nutanix/prism/utils/HttpUtilsTest.java
Labels: dev

#611 added outputs for get task details action.
  cs-nutanix-prism/src/main/java/io/cloudslang/content/nutanix/prism/actions/tasks/GetTaskDetails.java
Labels: dev

#612 Updated description for inputs.
  cs-oracle-cloud/src/main/java/io/cloudslang/content/oracle/oci/services/InstanceImpl.java
  cs-oracle-cloud/src/main/java/io/cloudslang/content/oracle/oci/services/SignerImpl.java
  cs-oracle-cloud/src/main/java/io/cloudslang/content/oracle/oci/utils/HttpUtils.java
Labels: dev

#613 Added Nutanix detach disks and delete nic operations.
  cs-nutanix-prism/src/main/java/io/cloudslang/content/nutanix/prism/actions/disks/DetachDisks.java
  cs-nutanix-prism/src/main/java/io/cloudslang/content/nutanix/prism/actions/nics/DeleteNIC.java
  cs-nutanix-prism/src/main/java/io/cloudslang/content/nutanix/prism/entities/NutanixDeleteNICInputs.java
  cs-nutanix-prism/src/main/java/io/cloudslang/content/nutanix/prism/entities/NutanixDetachDisksInputs.java
  cs-nutanix-prism/src/main/java/io/cloudslang/content/nutanix/prism/exceptions/NutanixDetachDiskException.java
  cs-nutanix-prism/src/main/java/io/cloudslang/content/nutanix/prism/service/DiskImpl.java
  cs-nutanix-prism/src/main/java/io/cloudslang/content/nutanix/prism/service/NicImpl.java
  cs-nutanix-prism/src/main/java/io/cloudslang/content/nutanix/prism/service/models/disks/DetachDisksRequestBody.java
  cs-nutanix-prism/src/main/java/io/cloudslang/content/nutanix/prism/utils/Constants.java
  cs-nutanix-prism/src/main/java/io/cloudslang/content/nutanix/prism/utils/Descriptions.java
  cs-nutanix-prism/src/main/java/io/cloudslang/content/nutanix/prism/utils/HttpUtils.java
  cs-nutanix-prism/src/main/java/io/cloudslang/content/nutanix/prism/utils/Inputs.java
  cs-nutanix-prism/src/test/java/io/cloudslang/content/nutanix/prism/services/DiskImplTest.java
  cs-nutanix-prism/src/test/java/io/cloudslang/content/nutanix/prism/services/NICImpl.java
Labels: dev

#618 Added the counter operation action class.
  cs-nutanix-prism/license.template
  cs-nutanix-prism/src/main/java/io/cloudslang/content/nutanix/prism/actions/disks/AttachDisks.java
  cs-nutanix-prism/src/main/java/io/cloudslang/content/nutanix/prism/actions/disks/DetachDisks.java
  cs-nutanix-prism/src/main/java/io/cloudslang/content/nutanix/prism/actions/nics/AddNic.java
  cs-nutanix-prism/src/main/java/io/cloudslang/content/nutanix/prism/actions/nics/DeleteNIC.java
  cs-nutanix-prism/src/main/java/io/cloudslang/content/nutanix/prism/actions/tasks/GetTaskDetails.java
  cs-nutanix-prism/src/main/java/io/cloudslang/content/nutanix/prism/actions/utils/Counter.java
  cs-nutanix-prism/src/main/java/io/cloudslang/content/nutanix/prism/actions/virtualmachines/CreateVM.java
  cs-nutanix-prism/src/main/java/io/cloudslang/content/nutanix/prism/actions/virtualmachines/DeleteVM.java
  cs-nutanix-prism/src/main/java/io/cloudslang/content/nutanix/prism/actions/virtualmachines/GetVMDetails.java
  cs-nutanix-prism/src/main/java/io/cloudslang/content/nutanix/prism/actions/virtualmachines/ListVMs.java
  cs-nutanix-prism/src/main/java/io/cloudslang/content/nutanix/prism/actions/virtualmachines/SetVMPowerState.java
  cs-nutanix-prism/src/main/java/io/cloudslang/content/nutanix/prism/entities/NutanixAttachDisksInputs.java
  cs-nutanix-prism/src/main/java/io/cloudslang/content/nutanix/prism/service/NicImpl.java
  cs-nutanix-prism/src/main/java/io/cloudslang/content/nutanix/prism/services/CounterImpl.java
  cs-nutanix-prism/src/main/java/io/cloudslang/content/nutanix/prism/services/DiskImpl.java
  cs-nutanix-prism/src/main/java/io/cloudslang/content/nutanix/prism/services/HttpCommons.java
  cs-nutanix-prism/src/main/java/io/cloudslang/content/nutanix/prism/services/NicImpl.java
  cs-nutanix-prism/src/main/java/io/cloudslang/content/nutanix/prism/services/TaskImpl.java
  cs-nutanix-prism/src/main/java/io/cloudslang/content/nutanix/prism/services/VMImpl.java
  cs-nutanix-prism/src/main/java/io/cloudslang/content/nutanix/prism/services/models/disks/AttachDisksRequestBody.java
  cs-nutanix-prism/src/main/java/io/cloudslang/content/nutanix/prism/services/models/disks/DetachDisksRequestBody.java
  cs-nutanix-prism/src/main/java/io/cloudslang/content/nutanix/prism/services/models/nics/AddNicRequestBody.java
  cs-nutanix-prism/src/main/java/io/cloudslang/content/nutanix/prism/services/models/virtualmachines/CreateVMRequestBody.java
  cs-nutanix-prism/src/main/java/io/cloudslang/content/nutanix/prism/services/models/virtualmachines/SetVMPowerStateRequestBody.java
  cs-nutanix-prism/src/main/java/io/cloudslang/content/nutanix/prism/utils/Constants.java
  cs-nutanix-prism/src/main/java/io/cloudslang/content/nutanix/prism/utils/CounterProcessor.java
  cs-nutanix-prism/src/main/java/io/cloudslang/content/nutanix/prism/utils/Descriptions.java
  cs-nutanix-prism/src/main/java/io/cloudslang/content/nutanix/prism/utils/HttpUtils.java
  cs-nutanix-prism/src/test/java/io/cloudslang/content/nutanix/prism/services/DiskImplTest.java
  cs-nutanix-prism/src/test/java/io/cloudslang/content/nutanix/prism/services/NICImplTest.java
  cs-nutanix-prism/src/test/java/io/cloudslang/content/nutanix/prism/services/TaskImplTest.java
  cs-nutanix-prism/src/test/java/io/cloudslang/content/nutanix/prism/services/VMImplTest.java
Labels: dev

#624 Updated general error handling of operations.
  cs-nutanix-prism/src/main/java/io/cloudslang/content/nutanix/prism/actions/tasks/GetTaskDetails.java
  cs-nutanix-prism/src/main/java/io/cloudslang/content/nutanix/prism/utils/Constants.java
  cs-nutanix-prism/src/main/java/io/cloudslang/content/nutanix/prism/utils/HttpUtils.java
Labels: dev

#627 Added private Key File property to perform OCI rest operations
  cs-oracle-cloud/src/main/java/io/cloudslang/content/oracle/oci/actions/instances/CreateInstance.java
  cs-oracle-cloud/src/main/java/io/cloudslang/content/oracle/oci/actions/instances/GetInstanceDefaultCredentials.java
  cs-oracle-cloud/src/main/java/io/cloudslang/content/oracle/oci/actions/instances/GetInstanceDetails.java
  cs-oracle-cloud/src/main/java/io/cloudslang/content/oracle/oci/actions/instances/ListInstances.java
  cs-oracle-cloud/src/main/java/io/cloudslang/content/oracle/oci/actions/vnics/GetVnicDetails.java
  cs-oracle-cloud/src/main/java/io/cloudslang/content/oracle/oci/actions/vnics/ListVnicAttachments.java
  cs-oracle-cloud/src/main/java/io/cloudslang/content/oracle/oci/entities/inputs/OCICommonInputs.java
  cs-oracle-cloud/src/main/java/io/cloudslang/content/oracle/oci/services/InstanceImpl.java
  cs-oracle-cloud/src/main/java/io/cloudslang/content/oracle/oci/services/SignerImpl.java
  cs-oracle-cloud/src/main/java/io/cloudslang/content/oracle/oci/services/VnicImpl.java
  cs-oracle-cloud/src/main/java/io/cloudslang/content/oracle/oci/utils/Constants.java
  cs-oracle-cloud/src/main/java/io/cloudslang/content/oracle/oci/utils/Descriptions.java
  cs-oracle-cloud/src/main/java/io/cloudslang/content/oracle/oci/utils/Inputs.java
  cs-oracle-cloud/src/main/java/io/cloudslang/content/oracle/oci/utils/InputsValidation.java
  cs-oracle-cloud/src/test/java/io/cloudslang/content/oracle/oci/utils/InputsValidationUtilsTest.java
Labels: dev

#626 Change csssh version and update bcprov-jdk15on
  cs-mail/pom.xml
  cs-utilities/pom.xml
Labels: dependencies

#643 Added potential malicious char escape in abbyy
  cs-abbyy/src/main/java/io/cloudslang/content/abbyy/entities/responses/HttpClientResponse.java
  cs-abbyy/src/main/java/io/cloudslang/content/abbyy/http/HttpClient.java
  cs-abbyy/src/main/java/io/cloudslang/content/abbyy/services/ProcessImageService.java
  cs-abbyy/src/main/java/io/cloudslang/content/abbyy/services/ProcessTextFieldService.java
  cs-abbyy/src/main/java/io/cloudslang/content/abbyy/utils/EncodingUtils.java
  cs-abbyy/src/main/java/io/cloudslang/content/abbyy/validators/XmlResultValidator.java
  cs-abbyy/src/test/java/io/cloudslang/content/abbyy/utils/EncodingUtilsTest.java
Labels: kind/enhancement

#642 Made changes in workspace variables
  cs-hashicorp-terraform/src/main/java/io/cloudslang/content/hashicorp/terraform/services/WorkspaceVariableImpl.java
  cs-hashicorp-terraform/src/main/java/io/cloudslang/content/hashicorp/terraform/utils/Descriptions.java
Labels: dev

#644 Escaped chars in abbyy with different strategy for xml
  cs-abbyy/src/main/java/io/cloudslang/content/abbyy/services/ProcessImageService.java
  cs-abbyy/src/main/java/io/cloudslang/content/abbyy/services/ProcessTextFieldService.java
  cs-abbyy/src/main/java/io/cloudslang/content/abbyy/utils/EncodingUtils.java
  cs-abbyy/src/test/java/io/cloudslang/content/abbyy/utils/EncodingUtilsTest.java
Labels: kind/bug

#645 Updated the attach_disks operation and description of operations.
  cs-nutanix-prism/src/main/java/io/cloudslang/content/nutanix/prism/actions/disks/AttachDisks.java
  cs-nutanix-prism/src/main/java/io/cloudslang/content/nutanix/prism/actions/virtualmachines/CreateVM.java
  cs-nutanix-prism/src/main/java/io/cloudslang/content/nutanix/prism/entities/NutanixAttachDisksInputs.java
  cs-nutanix-prism/src/main/java/io/cloudslang/content/nutanix/prism/exceptions/NutanixDetachDiskException.java
  cs-nutanix-prism/src/main/java/io/cloudslang/content/nutanix/prism/services/DiskImpl.java
  cs-nutanix-prism/src/main/java/io/cloudslang/content/nutanix/prism/services/VMImpl.java
  cs-nutanix-prism/src/main/java/io/cloudslang/content/nutanix/prism/services/models/disks/AttachDisksRequestBody.java
  cs-nutanix-prism/src/main/java/io/cloudslang/content/nutanix/prism/services/models/virtualmachines/CreateVMRequestBody.java
  cs-nutanix-prism/src/main/java/io/cloudslang/content/nutanix/prism/utils/Constants.java
  cs-nutanix-prism/src/main/java/io/cloudslang/content/nutanix/prism/utils/Descriptions.java
  cs-nutanix-prism/src/main/java/io/cloudslang/content/nutanix/prism/utils/Inputs.java
  cs-nutanix-prism/src/test/java/io/cloudslang/content/nutanix/prism/services/DiskImplTest.java
Labels: dev
